name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a build.sh
        run: bash build.sh
        shell: bash
      - name: Archive artifacts (jar)
        uses: actions/upload-artifact@v2
        with:
          name: artifacts-jar
          path: target/*.jar
  deployment_staging:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifacts-jar
      - name: Update deployment theme
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ACCOUNT_EMAIL: ${{ secrets.ACCOUNT_EMAIL }}
          ACCOUNT_PASSWORD: ${{ secrets.ACCOUNT_PASSWORD }}
          ENDPOINT_IAM: ${{ secrets.ENDPOINT_IAM }}
          ENDPOINT_API: ${{ secrets.ENDPOINT_API }}
          DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}
        run: |
          ACCESS_TOKEN=$(curl -s -q $ENDPOINT_IAM/auth/realms/cloud-iam/protocol/openid-connect/token -d "grant_type=password&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&username=$ACCOUNT_EMAIL&password=$ACCOUNT_PASSWORD" | jq -r .access_token)
          curl -v --location --request PUT "${ENDPOINT_API}/deployments/${DEPLOYMENT_ID}/extensions/jars/4c2caa9e-ee4b-4494-8834-f1b25e9ea147" --header "Authorization: Bearer ${ACCESS_TOKEN}" --form 'extension=@cloud-iam-redesign-2.0.0-SNAPSHOT.jar' --http1.1
#  deployment_production:
#    needs: build
#    runs-on: ubuntu-latest
#    environment: production
#    steps:
#      - uses: actions/download-artifact@v2
#        with:
#          name: artifacts-jar
#      - name: Curl a deployment
#        env:
#          CLIENT_ID: ${{ secrets.CLIENT_ID }}
#          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#          ACCOUNT_EMAIL: ${{ secrets.ACCOUNT_EMAIL }}
#          ACCOUNT_PASSWORD: ${{ secrets.ACCOUNT_PASSWORD }}
#          ENDPOINT_IAM: ${{ secrets.ENDPOINT_IAM }}
#          ENDPOINT_API: ${{ secrets.ENDPOINT_API }}
#          DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}
#        run: |
#          ACCESS_TOKEN=$(curl -s -q $ENDPOINT_IAM/auth/realms/cloud-iam/protocol/openid-connect/token -d "grant_type=password&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&username=$ACCOUNT_EMAIL&password=$ACCOUNT_PASSWORD" | jq -r .access_token)
#          curl -v --location --request PUT "${ENDPOINT_API}/deployments/${DEPLOYMENT_ID}/extensions/jars" --header "Authorization: Bearer ${ACCESS_TOKEN}" --form 'extension=@cloud-iam-theme-1.0.0-SNAPSHOT.jar' --http1.1
